#!/bin/sh
# Checks internet every second until it comes back,
# plays an auditory message when it returns.

alias myip="curl -s ifconfig.co";
SLEEP_INT=$([ -n "$1" ] && echo "$1" || echo '1');

until [ "$(myip)" ];
	do sleep "$SLEEP_INT";
done;
notify-say ' internet online' "ip address $(myip)";
