#!/bin/sh
# Show the current sxhkd keybindings
# Change inter-column padding with this ▼ number
awk '/^[a-z]/ && last {print sprintf("%-35s",$0),"\t",last} {last=""} /^#/{last=$0}' "$XDG_CONFIG_HOME/sxhkd/sxhkdrc"
