#!/bin/sh
# Open/Unlock a hotplugged LUKS device with rofi prompt

hotluks="$(lsblk -rpo "name,hotplug,fstype,size,mountpoint" | awk '$2==1&&$3=="crypto_LUKS"&&$5==""{printf "%s (%s)\n",$1,$4}')";

openluks() { \
	chosen="$(echo "$hotluks" | rofi -dmenu -i -p "Open which LUKS drive?" | awk '{print $1}')";
	if [ -n "$chosen" ]; then
		mapped=$(echo "$chosen" | awk -F '/' '{print $NF 1}');
		sudo -A cryptsetup luksOpen "$chosen" "$mapped";
		exit_code=$?;
		if [ "$exit_code" -eq 0 ]; then
			notify-send " LUKS opening" "$chosen opened.";
		else
			notify-send " LUKS error ($exit_code)" "couldn't open $chosen."
			exit "$exit_code";
		fi;
	fi;
}

if [ -n "$hotluks" ]; then
	openluks;
else
	notify-send ' LUKS open failed' 'no openable luks device found';
fi;
