#!/bin/sh
# Open/Unlock a hotplugged LUKS device with rofi prompt
# Must be executed from the terminal - I don't have a secure way of
# Sending the LUKS password graphically yet.

hotluks="$(lsblk -rpo "name,hotplug,fstype,size,mountpoint" | awk '$2==1&&$3=="crypto_LUKS"&&$5==""{printf "%s (%s)\n",$1,$4}')";

openluks() { \
	chosen="$(echo "$hotluks" | rofi -dmenu -i -p "Open which LUKS drive?" | awk '{print $1}')";
	if [ -n "$chosen" ]; then
		mapped=$(echo "$chosen" | awk -F '/' '{print $NF 1}');
		sudo -A cryptsetup luksOpen "$chosen" "$mapped" && notify-send " LUKS opening" "$chosen opened." && exit 0;
	else
		exit 2;
	fi;
}

if [ -n "$hotluks" ]; then
	openluks;
else
	notify-send ' LUKS' 'no luks device found';
fi;
