#!/bin/sh
# Gives a rofi prompt to mount unmounted drives.
# If they're in /etc/fstab, they'll be mounted automatically.
# Otherwise, you'll be prompted to give a mountpoint from already existsing directories.
# If you input a novel directory, it will prompt you to create that directory.

NHEADER="💾 rmount"

getmount() { \
	[ -z "$chosen" ] && exit 1;
	mp="$(fd -IL -t 'd' --exact-depth 2 . "$HOME/mnt" | rofi -dmenu -i -p "$NHEADER" -mesg "Mount $chosen where?")";
	[ "$mp" = "" ] && exit 1;
	if [ ! -d "$mp" ]; then
		mkdiryn=$(printf "No\\nYes" | rofi -dmenu -i -p "$NHEADER" -mesg "$mp does not exist. Create it?");
		[ "$mkdiryn" = "Yes" ] && (mkdir -p "$mp" || sudo -A mkdir -p "$mp");
	fi
}

mountusb() { \
	chosen="$(echo "$usbdrives" | rofi -dmenu -i -p "$NHEADER" -mesg 'Mount which USB drive?' | awk '{print $1}')";
	sudo -A mount "$chosen" && notify-send "$NHEADER" "$chosen USB drive mounted" && exit 0;
	alreadymounted=$(lsblk -nrpo "name,type,mountpoint" | awk '$2=="part"&&$3!~/\/boot|\/home$|SWAP/&&length($3)>1{printf "-not \( -path *%s -prune \) \ \n",$3}');
	getmount "/mnt /media /mount /home -maxdepth 5 -type d $alreadymounted";
	partitiontype="$(lsblk -no \"fstype\" "$chosen")";
	case "$partitiontype" in
		"vfat") sudo -A mount -t vfat "$chosen" "$mp" -o rw,umask=0000;;
		*) sudo -A mount "$chosen" "$mp"; user="$(whoami)"; ug="$(groups | awk '{print $1}')"; sudo -A chown "$user":"$ug" 741 "$mp";;
	esac;
	notify-send "$NHEADER" "$chosen USB drive mounted to $mp";
}

mountandroid() { \
	chosen=$(echo "$anddrives" | rofi -dmenu -i -p "$NHEADER" -mesg "Mount which Android device?" | cut -d : -f 1);
	getmount "$HOME -maxdepth 3 -type d";
	simple-mtpfs --device "$chosen" "$mp";
	notify-send "$NHEADER" "$chosen Android device mounted to $mp";
}

asktype() { \
	case $(printf "USB\\nAndroid" | rofi -dmenu -i -p "$NHEADER" -mesg "Mount a USB drive or Android device?") in
		USB) mountusb ;;
		Android) mountandroid ;;
	esac
}

anddrives=$(simple-mtpfs -l 2>/dev/null);
usbdrives="$(lsblk -rpo 'name,type,size,mountpoint' | awk '$2=="part"||$2=="crypt"&&$4==""{printf "%s (%s)\n",$1,$3}')";
#usbdrives=$(lsblk -nrpo "name,type,size,mountpoint" | awk '($2=="part"||$2=="crypt")&&$4!~/\/boot|\/home$|SWAP/&&length($4)>1{printf "%s (%s)\n",$4,$3}');

if [ -z "$usbdrives" ]; then
	[ -z "$anddrives" ] && notify-send "$NHEADER" "No mountable drive found" && exit 0;
	notify-send "$NHEADER" "Mountable Android device found"
	mountandroid;
else
	if [ -z "$anddrives" ]; then
		notify-send "$NHEADER" "Mountable USB drive found"
		mountusb;
	else
		notify-send "$NHEADER" "Mountable USB drive and Android device found"
		asktype;
	fi;
fi;
