#!/bin/sh
# Run a custom chosen peaclock function from the peaclock config directory

NHEADER="⏲ rpeaclock";
chosen=$(fd '[^\.gitignore]' --regex -t 'f' -d 1 "$XDG_CONFIG_HOME/peaclock"| sed 's!.*/!!' | rofi -show -dmenu -i -l 7 -p "$NHEADER" -mesg 'choose peaclock function');
exit_code=$?;

if [ "$exit_code" -eq 0 ]; then
	notify-send "$NHEADER" "$chosen started";
	peaclock --config-dir="$XDG_CONFIG_HOME/peaclock" --config="$XDG_CONFIG_HOME/peaclock/$chosen";
	exit 0;
else
	notify-send "$NHEADER" "cancelled" && exit "$exit_code";
fi;
