#!/bin/sh
# A rofi prompt to unmount drives.
# Provides you with mounted partitions, select one to unmount.
# Starts rluksclose prompt if the drive has lsblk type 'crypt'.
# Drives mounted at /, /boot and /home will not be options to unmount.

unmountusb() {
	[ -z "$drives" ] && exit;
	chosen=$(echo "$drives" | rofi -dmenu -i -p "Unmount which drive?" | awk '{print $1}');
	isluks=$(lsblk -rpo "name,type,size,fstype,mountpoint" | awk '$2=="crypt"&&$4!="LVM2_member"{printf "%s %s\n", $1, $5}' | grep "$chosen");
	[ -z "$chosen" ] && exit;
	sudo -A umount "$chosen" && notify-send "💻 USB unmounting" "$chosen unmounted.";
	[ -z "$isluks" ] && exit;
	rluksclose;
}

unmountandroid() { \
	chosen=$(awk '/simple-mtpfs/ {print $2}' /etc/mtab | rofi -dmenu -i -p "Unmount which device?");
	[ -z "$chosen" ] && exit;
	sudo -A umount -l "$chosen" && notify-send "🤖 Android unmounting" "$chosen unmounted.";
}

asktype() { \
	case "$(printf "USB\\nAndroid" | rofi -dmenu -i -p "Unmount a USB drive or Android device?")" in
		USB) unmountusb ;;
		Android) unmountandroid ;;
	esac;
}

drives=$(lsblk -nrpo "name,type,size,mountpoint" | awk '($2=="part"||$2=="crypt")&&$4!~/\/boot|\/home$|SWAP/&&length($4)>1{printf "%s (%s)\n",$4,$3}');

if ! grep simple-mtpfs /etc/mtab; then
	[ -z "$drives" ] && echo "No drives to unmount." && exit;
	echo "Unmountable USB drive detected.";
	unmountusb;
else
	if [ -z "$drives" ]
	then
		echo "Unmountable Android device detected.";
		unmountandroid;
	else
		echo "Unmountable USB drive(s) and Android device(s) detected.";
		asktype;
	fi;
fi;

