#!/bin/sh
# If transmission-daemon is running, will ask to kill, else will ask to start.

if pgrep -x transmission-da >/dev/null ; then
	[ "$(printf "No\\nYes" | rofi -show -dmenu -i -p "Kill transmission-daemon?")" = "Yes" ] && killall transmission-daemon && notify-send 'td-toggle' 'transmission-daemon killed.'
else
	ifinstalled transmission-cli || exit
	[ "$(printf "No\\nYes" | rofi -show -dmenu -i -p "Start transmission daemon?")" = "Yes" ] && transmission-daemon && notify-send 'td-toggle' 'tranmission-daemon started.'
fi;
