#!/bin/sh
#      __               __
#     / /_  ____ ______/ /____  ______
#    / __ \/ __ `/ ___/ //_/ / / / __ \
#   / /_/ / /_/ / /__/ ,< / /_/ / /_/ /
#  /_.___/\__,_/\___/_/|_|\__,_/ .___/
#                             /_/
# local drive backup script.
# Used for 'AB' tagged drives

BK_SRC="$HOME";
BK_MOUNT='/mnt/usb/archive_a';
BK_DEST="$BK_MOUNT"'/archive';

echo 'starting backup from' "$BK_SRC" 'to' "$BK_DEST"'...';
echo 'make sure backup drive is mounted at' "$BK_MOUNT";

if [ "$(mount | grep -c $BK_MOUNT)" = 0 ] ; then
	echo 'no drive found mounted at' "$BK_MOUNT";
	echo 'exiting without backing up data';
	exit 1;
fi;

alias appsync='rsync -avxP';
alias mirsync='rsync -avxP --delete';

echo 'scripts/keys...';
appsync "$BK_SRC"'/.local/' "$BK_DEST"'/.local/';
appsync "$BK_SRC"'/.ssh/' "$BK_DEST"'/.ssh/';

echo 'config...';
mirsync "$BK_SRC"'/.config/' "$BK_DEST"'/.config/';
mirsync "$BK_SRC"'/.gitconfig' "$BK_DEST"'/.gitconfig';
mirsync "$BK_SRC"'/.tmux.conf' "$BK_DEST"'/.tmux.conf';

echo 'dotfiles...'
mirsync "$BK_SRC"'/.bash_logout' "$BK_DEST"'/.bash_logout';
mirsync "$BK_SRC"'/.bash_profile' "$BK_DEST"'/.bash_profile';
mirsync "$BK_SRC"'/.bashrc' "$BK_DEST"'/.bashrc';
mirsync "$BK_SRC"'/.inputrc' "$BK_DEST"'/.inputrc';
mirsync "$BK_SRC"'/.profile' "$BK_DEST"'/.profile';
mirsync "$BK_SRC"'/.Xdefaults' "$BK_DEST"'/.Xdefaults';
mirsync "$BK_SRC"'/.xinitrc' "$BK_DEST"'/.xinitrc';
mirsync "$BK_SRC"'/.xonshrc' "$BK_DEST"'/.xonshrc';
mirsync "$BK_SRC"'/.xprofile' "$BK_DEST"'/.xprofile';
mirsync "$BK_SRC"'/.Xresources' "$BK_DEST"'/.Xresources';
mirsync "$BK_SRC"'/.xsession' "$BK_DEST"'/.xsession';
mirsync "$BK_SRC"'/.zprofile' "$BK_DEST"'/.zprofile';

echo 'work...';
mirsync "$BK_SRC"'/crunch/' "$BK_DEST"'/crunch/';
mirsync "$BK_SRC"'/crunch-thesis/' "$BK_DEST"'/crunch-thesis/';

echo 'data...';
appsync "$BK_SRC"'/Documents/' "$BK_DEST"'/Documents/';
appsync "$BK_SRC"'/Pictures/' "$BK_DEST"'/Pictures/';
appsync "$BK_SRC"'/Projects/' "$BK_DEST"'/Projects/';
mirsync "$BK_SRC"'/Music/' "$BK_DEST"'/Music/';
mirsync "$BK_SRC"'/vimwiki/' "$BK_DEST"'/vimwiki/';
mirsync "$BK_SRC"'/Templates/' "$BK_DEST"'/Templates/';

echo 'generic backup...';
appsync "$BK_SRC"'/backup/*' "$BK_DEST"'/';

echo 'update record...'
date +'%Y-%m-%d_%r' | sed s/\ //g >> "$BK_DEST"'/archives.txt';
