#!/bin/sh
#      __    __               __
#     / /_  / /_  ____ ______/ /____  ______
#    / __ \/ __ \/ __ `/ ___/ //_/ / / / __ \
#   / /_/ / /_/ / /_/ / /__/ ,< / /_/ / /_/ /
#  /_.___/_.___/\__,_/\___/_/|_|\__,_/ .___/
#                                   /_/
# backup (B) and backup-crossplatform (BC) drive backup script.
BK_SRC="$HOME";
BK_MOUNT='/mnt/usb/generic_a';
BK_DEST="$BK_MOUNT";
BK_TYPE=$(basename "$0");

echo 'starting backup from' "$BK_SRC" 'to' "$BK_DEST"'...';
echo 'make sure backup drive is mounted at' "$BK_MOUNT";

if [ "$(mount | grep -c $BK_MOUNT)" = 0 ] ; then
	echo 'no drive found mounted at' "$BK_MOUNT";
	echo 'exiting without backing up data';
	exit 1;
fi;

alias appsync='sudo rsync -avxP';
alias mirsync='sudo rsync -avxP --delete';

echo 'generic backup...';
appsync "$BK_SRC"'/backup/' "$BK_DEST"'/';

echo 'update record...';
date +'%Y-%m-%d_%r' | sed s/\ //g >> "$BK_DEST/$BK_TYPE.txt";

echo 'script complete';
notify-say "$BK_TYPE" 'backup done';

