#!/bin/sh
#        _)     _)        _|
#    _` | |  __| | __ \  |    _ \
#   (   | | |    | |   | __| (   |
#  \__,_|_|_|   _|_|  _|_|  \___/
# Air Quality Index query script.
# Inspired by: https://github.com/polybar/polybar-scripts/tree/master/polybar-scripts/info-airqualityindex
# API Docs: https://aqicn.org/json-api/doc/
#
# This script sends a request to the Air Quality Open Data Platform to get the air index quality at the specified locale.
# A valid api key is required to be in a text file at $KEY_FILE (set to ~/.config/api-keys/airqualityindex-0.txt by default).
#
# The location can be set via the commandline argument (see geoloc), otherwise the default option will be used.
# Dependencies: geoloc, curl, jq, tr, sed

LOC=$(geoloc "$1" | tr ',' ';' | sed 's/^/geo:/;');
KEY_FILE="$HOME/.config/api-keys/airqualityindex-0.txt";
BASE_URL="https://api.waqi.info/feed";

if [ -f "$KEY_FILE" ]; then
	API_KEY=$(sed 1q "$KEY_FILE");
	RETVAL=$(curl -sf "$BASE_URL/$LOC/?token=$API_KEY");

	if [ -n "$RETVAL" ]; then
		if [ "$(echo "$RETVAL" | jq -r '.status')" = "ok" ]; then
			echo "$RETVAL" | jq '.data.aqi';
			exit 0;
		fi;
	fi;
else
	echo "Airqualityindex API key file must be here: $KEY_FILE";
fi;
exit 1;
