#!/bin/sh
#           __      __                            __
#    ____ _/ /___  / /_  ____ _____ ___  ______  / /____
#   / __ `/ / __ \/ __ \/ __ `/ __ `/ / / / __ \/ __/ _ \
#  / /_/ / / /_/ / / / / /_/ / /_/ / /_/ / /_/ / /_/  __/
#  \__,_/_/ .___/_/ /_/\__,_/\__, /\__,_/\____/\__/\___/
#        /_/                   /_/
# Alpha Vantage intraday price query script.
# API Docs: https://www.alphavantage.co/documentation/
#
# Commandline Args:
# 	* $1 (frequency),  valid values are in {1, 5, 15, 30, 60}.
# 	* $2 (symbol), valid Alpha Vantage symbol (ie '^SPX')
# A valid api key is required to be in a text file at $KEY_FILE (set to ~/.config/api-keys/alphavantage-0.txt by default).
# Dependencies: sed, curl

FREQ=$1;
SYMBOL=$([ -n "$2" ] && echo "$2" || echo '^SPX');
FUNCTION='TIME_SERIES_INTRADAY';
KEY_FILE="$HOME/.config/api-keys/alphavantage-0.txt";
BASE_URL='https://www.alphavantage.co/query';

if [ -f "$KEY_FILE" ]; then
	API_KEY=$(sed 1q "$KEY_FILE");
	INTERVAL="$FREQ"'min';
	curl -s -N "$BASE_URL?apikey=$API_KEY&function=$FUNCTION&symbol=$SYMBOL&interval=$INTERVAL&outputsize=full&datatype=csv" && exit 0;
else
	echo "Alpha Vantage API key file must be here: $KEY_FILE" && exit 1;
fi;
