#!/bin/sh
#                   |                             |
#    _` | __ \   _` | __ `__ \   _ \  |   | __ \  __|
#   (   | |   | (   | |   |   | (   | |   | |   | |
#  \__,_|_|  _|\__,_|_|  _|  _|\___/ \__,_|_|  _|\__|
# Android device mounting script.
# Mounts the first android device found by simple-mtpfs

MOUNT_LOC="$HOME"'/mnt/android/phone_a/';
anddrives=$(simple-mtpfs -l 2>/dev/null);

[ -z "$anddrives" ] && echo "No Android device detected" && exit;
notify-send "🤖 Android device(s)" "$anddrives";

simple-mtpfs --device 1 "$MOUNT_LOC";
notify-send "🤖 Android Mounting" "Android device mounted to $MOUNT_LOC";
