#!/bin/sh
# TODO playlists instead of music

NHEADER="🎼 $(basename "$0")"
BASEDIR="$HOME/Music/"
MESG="Which music?"

sel=$(fd -I . --base-directory="$BASEDIR" -e 'mp3' | rofi -lines 10 -dmenu -i -p "$NHEADER" -mesg "$MESG");

if [ -n "$sel" ] ; then
	notify-send "$NHEADER" "$sel";
	xdg-open "$BASEDIR/$sel";
else
	notify-send "$NHEADER" "cancelled";
fi;

