#!/bin/sh

COU="United_States";
CITY="";
alias sstart="sudo -A systemctl start" \
	sstop="sudo -A systemctl stop" \
	srestart="sudo -A systemctl restart";

if nordvpn status | grep -q 'Status: Connected'; then
	nordvpn set killswitch off && nordvpn d && sstop nordvpnd && notify-send '嬨nordvpnd' 'stopped' && srestart NetworkManager && notify-send 'NetworkManager' 'restarted';
else
	sstart nordvpnd && notify-send '嬨nordvpnd' 'started' && nordvpn set killswitch on && nordvpn c "$COU" "$CITY";
fi;
