#!/bin/sh
#        _/_/  _/            _/    _/
#     _/          _/_/_/        _/_/_/_/    _/_/
#  _/_/_/_/  _/  _/    _/  _/    _/      _/    _/
#   _/      _/  _/    _/  _/    _/      _/    _/
#  _/      _/  _/    _/  _/      _/_/    _/_/

CURTIME=$(date +"%I:%M %p");
CNT=1;

while [ $CNT -gt 0 ]; do
	notify-say "$1" "$CURTIME";
	CNT=$(( CNT - 1 )); sleep 0.2;
done;
