#!/bin/sh
#   _     _
#  | |__ | |__
#  | '_ \| '_ \
#  | | | | | | |
#  |_| |_|_| |_|
# Main help-house access script.
# Opens the selected help-house file (how.md, what.md, where.md) in markdown viewer with paging.
# Usage: hh -f <helpfile> -q <query>
# Options:
#	-f: (optional) specify helpfile
#		* how.md (default)
#		* what.md
#		* where.md
#	-q: (optional) fzf query string to prefilter options
#	-h: print usage

HH_DIR="$HOME/Projects/help-house";
file="how.md";
query="";

_usage() {
	printf "Usage: hh -f <helpfile> -q <query>\nOptions:\n\t-f: (optional) specify helpfile\n\t\t* how.md (default)\n\t\t* what.md\n\t\t* where.md\n\t-q: (optional) fzf query string to prefilter options\n\t-h: print usage\n"
	exit 1;
}

while getopts "f:q:h?" arg; do
	case "$arg" in
		f) file=$OPTARG;;
		q) query=$OPTARG;;
		h|?|*) _usage;;
	esac;
done;

topic=$(fd "$file" --base-directory="$HH_DIR" | sort | fzf --query="$query")
notify-send "help-house" "$topic";
$PAGER "$HH_DIR/$topic"
