#!/bin/sh
# snippet to populate display variables, should be sourced

export DISPLAYS="$(xrandr | grep ' connected' | awk '{print $1}')";
export DISPLAY_DP="$(printf '%s' "$DISPLAYS" | grep '^DP.*' | head -1)";
export DISPLAY_HDMI="$(printf '%s' "$DISPLAYS" | grep '^HDMI.*' | head -1)";
export DISPLAY_EDP="$(printf '%s' "$DISPLAYS" | grep '^eDP.*' | head -1)";

