#!/bin/sh
# Switches the gpu used for graphics on startup between nvidia<->hybrid

if [ "$(gfxmode)" = 'nvidia' ]; then
	gfxstarthyb;
else
	gfxstartnvi;
fi

prompt 'Reboot computer?' 'sudo -A reboot';
