#!/bin/sh
# Switches the gpu used for graphics between nvidia<->hybrid
# Requires xorg restart to take into effect

if [ "$(gfxmode)" = 'nvidia' ]; then
	gfxswitchhyb;
else
	gfxswitchnvi;
fi

prompt 'Logout computer?' 'bspc quit';
