#!/bin/sh

# Switches the gpu used for graphics and automatically logs out i3 session

GPU_MODE=$(optimus-manager --print-mode | head -n 2 | xargs | awk '{print $NF}' | xargs);
SWITCH_TO=$([ "$GPU_MODE" = 'nvidia' ] && echo 'hybrid' || echo 'nvidia');

notify-send '🎮 switch gpu' "$GPU_MODE -> $SWITCH_TO";
optimus-manager --no-confirm --switch "$SWITCH_TO" >> /dev/null;
