#!/bin/sh

# Switches the gpu used for graphics on startup

START_GPU_MODE=$(optimus-manager --print-startup | awk '{print $NF}' | xargs);
SWITCH_TO=$([ "$START_GPU_MODE" = 'nvidia' ] && echo 'intel' || echo 'nvidia');

notify-send '🎮 switch startup gpu' "$START_GPU_MODE -> $SWITCH_TO";
optimus-manager --no-confirm --set-startup "$SWITCH_TO" >> /dev/null;
prompt 'Reboot computer?' 'sudo -A reboot';
