#!/bin/sh
# Switches the gpu used for graphics on startup

GPU_MODE=$(gfxmode);
notify-send '🎮 switch startup gpu' "current: $GPU_MODE";

[ "$GPU_MODE" = 'nvidia' ] && sudo envycontrol -s 'hybrid' --rtd3 || sudo envycontrol -s 'nvidia' --force-comp;
prompt 'Reboot computer?' 'sudo -A reboot';
