#!/bin/sh

# Sets the ldm-gtk-greeter background. If given an argument, will set file as ldm background.
[ ! -z "$1" ] && sudo cp "$1" /usr/share/pixmaps/ldm.png && notify-send -i "$HOME/.config/ldm.png" 'Lightdm bg changed.';
