#!/bin/sh
# Toggle floating dropdown terminal in i3, or start if non-existing.
# $1 is	the script run in the terminal.
# All other args are terminal settings.
#
# XXX Using the instance name to identify i3dd windows is not portable to some terminals like alacritty

[ -z "$1" ] && exit

script=$1
shift
if xwininfo -tree -root | grep "(\"i3dd-$script\" ";
then
	echo "Window detected.";
	i3 "[instance=\"i3dd-$script\"] scratchpad show; [instance=\"i3dd-$script\"] move position center";
else
	echo "Window not detected... spawning.";
	i3 "exec --no-startup-id $TERMINAL -n i3dd-$script $@ -e $script";
fi
