#!/bin/sh
# If transmission-daemon is running, will ask to kill, else will ask to start.

if pgrep -x transmission-da >/dev/null ; then
	(tprompty 'Kill transmission-daemon?' killall transmission-daemon) && notify-send 'td-toggle' 'transmission-daemon killed.'
else
	ifinstalled transmission-cli || exit
	(tprompty 'Start transmission-daemon?' transmission-daemon) && notify-send 'td-toggle' 'tranmission-daemon started.'
fi;
