#!/bin/sh
# Close/Lock a LUKS mapping with tofi prompt

NHEADER="🔒 tluksclose";

luksmaps="$(lsblk -rpo 'name,type,size,fstype,mountpoint' | awk '$2=="crypt"&&$4!="LVM2_member"&&$5==""{printf "%s (%s)\n",$1,$3}')";

[ -z "$luksmaps" ] && notify-send "⚠️$NHEADER" "no closeable luks device found" && exit 0;

chosen="$(echo "$luksmaps" | tofi --prompt-text "$NHEADER: Close which LUKS mapping?" | awk '{print $1}')";
[ -z "$chosen" ] && exit 0; # exit with 0 for chain-ability

cryptsetup luksClose "$chosen";
ec=$?;
[ "$ec" -eq 0 ] && notify-send "✔️$NHEADER" "$chosen closed" && exit 0;

notify-send "❌($ec)$NHEADER" "failed to close $chosen" && exit "$ec";
