#!/bin/sh
# Open/Unlock a hotplugged LUKS device with tofi prompt

NHEADER="🔒 tluksopen";
hotluks="$(lsblk -rpo 'name,hotplug,fstype,size,mountpoint' | awk '$2==1&&$3=="crypto_LUKS"&&$5==""{printf "%s (%s)\n",$1,$4}')";

openluks() { \
	chosen="$(echo "$hotluks" | tofi --prompt-text "$NHEADER: Open which LUKS drive?" | awk '{print $1}')";
	if [ -n "$chosen" ]; then
		mapped=$(echo "$chosen" | awk -F '/' '{print $NF 1}');
		sudo -A cryptsetup luksOpen "$chosen" "$mapped";
		exit_code=$?;
		if [ "$exit_code" -eq 0 ]; then
			notify-send "$NHEADER" "$chosen opened" && exit 0;
		else
			notify-send "$NHEADER" "couldn\'t open $chosen ($exit_code)" && exit "$exit_code";
		fi;
	else
		notify-send "$NHEADER" "luks open cancelled" && exit 0;
	fi;
}

if [ -n "$hotluks" ]; then
	openluks;
else
	notify-send "$NHEADER" "no openable luks device found" && exit 0;
fi;
