#!/bin/sh
# Open/Unlock a hotplugged LUKS map with tofi prompt

NHEADER="🔒 tluksopen";

luksmaps="$(lsblk -rpo 'name,hotplug,fstype,size,mountpoint' | awk '$2==1&&$3=="crypto_LUKS"&&$5==""{printf "%s (%s)\n",$1,$4}')";

[ -z "$luksmaps" ] && notify-send "⚠️$NHEADER" "no openable luks device found" && exit 0;

chosen="$(echo "$luksmaps" | tofi --prompt-text "$NHEADER: Open which luks device?" | awk '{print $1}')";
[ -z "$chosen" ] && exit 0; # exit with 0 for chain-ability

mapped=$(echo "$chosen" | awk -F '/' '{print $NF 1}');
cryptsetup luksOpen "$chosen" "$mapped";
ec=$?;
[ "$ec" -eq 0 ] && notify-send "✔️$NHEADER" "$chosen opened" && exit 0;

notify-send "❌($ec)$NHEADER" "failed to open $chosen" && exit "$ec";
