#!/bin/sh
# A tofi prompt to unmount drives.
# Provides you with mounted partitions, select one to unmount.
# Drives mounted at /, /boot and /home will not be options to unmount.

NHEADER="💾 tumount"

unmountusb() {
	[ -z "$drives" ] && exit 0;
	chosen="$(echo "$drives" | tofi --prompt-text "$NHEADER: unmount which usb drive?" | awk '{print $1}')";
	[ -z "$chosen" ] && exit 1;
	sudo -A umount "$chosen" && notify-send "$NHEADER" "$chosen usb drive unmounted" && exit 0;
}

unmountandroid() { \
	chosen=$(awk '/simple-mtpfs/ {print $2}' /etc/mtab | tofi --prompt-text "$NHEADER: Unmount which Android device?");
	[ -z "$chosen" ] && exit 1;
	sudo -A umount -l "$chosen" && notify-send "$NHEADER" "$chosen Android device unmounted" && exit 0;
}

asktype() { \
	case "$(printf "USB\\nAndroid" | tofi --prompt-text "$NHEADER: Unmount a USB drive or Android device?")" in
		USB) unmountusb ;;
		Android) unmountandroid ;;
	esac;
}

drives=$(lsblk -nrpo "name,type,size,mountpoint" | awk '($2=="part"||$2=="crypt")&&$4!~/\/boot|\/home$|SWAP/&&length($4)>1{printf "%s (%s)\n",$4,$3}');

if ! grep simple-mtpfs /etc/mtab; then
	[ -z "$drives" ] && notify-send "$NHEADER" "No umountable drive found" && exit 0;
	notify-send "$NHEADER" "Umountable USB drive found"
	unmountusb;
else
	if [ -z "$drives" ]; then
		notify-send "$NHEADER" "Umountable Android device found"
		unmountandroid;
	else
		notify-send "$NHEADER" "Umountable USB drive and Android device found"
		asktype;
	fi;
fi;

