#!/bin/sh

SPACES=$([ -n "$2" ] && echo "$2" || echo '4');
[ -z "$1" ] && printf "Must supply a filename to convert space indentation to tabs for\n" && exit 1;
mv -v "$1" "$1.original";
printf "converting %s to tab indentation (space ident of %s)...\n" "$1" "$SPACES";
unexpand --first-only -t "$SPACES" "$1.original" > "$1";
